#include <stdio.h>
#include <stdlib.h>

#define KGRN  "\x1B[32m"
#define KRED  "\x1B[31m"
#define KNRM  "\x1B[0m"

int main(){
	
	system("clear");
	
	printf("\n\n%sMovies watched in 2018:\n\n", KNRM);
	
	printf("%sA Quiet Place (2018)\n", KGRN);
	printf("%sA Silent Voice (2016)\n", KRED);
	printf("%sAdrift (2018)\n", KRED);
	printf("%sAnt-Man And The Wasp (2018)\n", KGRN);
	printf("%sAvengers: Infinity War (2018)\n", KGRN);
	printf("%sBaby Driver (2017)\n", KGRN);
	printf("%sBad Moms (2016)\n", KGRN);
	printd("%sBlack Panther (2018)\n", KGRN);
	printf("%sBlade Runner 2049 (2017)\n", KGRN);
	printf("%sBlockers (2018)\n", KGRN);
	printf("%sCasablanca (1942)\n", KRED);
	printf("%sCitizen Kane (1941)\n", KRED);
	printf("%sCoco (2017)\n", KGRN);
	printf("%sDeadpool 2 (2018)\n", KGRN);
	printf("%sDeath Wish (2018)\n", KGRN);
	printf("%sDeliver Us From Evil (2014)\n", KGRN);
	printf("%sDunkirk (2017)\n", KGRN);
	printf("%sEasy A (2010)\n", KGRN);
	printf("%sEighth Grade (2018)\n", KGRN);
	printf("%sGame Night (2018)\n", KGRN);
	printf("%sGodzilla: Planet Of The Monsters (2017)\n", KGRN);
	printf("%sGone With The Wind (1939)\n", KRED);
	printf("%sHall Pass (2011)\n", KGRN);
	printf("%sI, Tonya (2017)\n", KGRN);
	printf("%sIncredibles 2 (2018)\n", KRED);
	printf("%sJumanji: Welcome To The Jungle (2017)\n", KGRN);
	printf("%sJurassic World: Fallen Kingdom (2018)\n", KGRN);
	printf("%sKingsglaive: Final Fantasy XV (2016)\n", KGRN);
	printf("%sLaggies (2014)\n", KGRN);
	printf("%sLike Father (2018)\n", KGRN);
	printf("%sLions For Lambs (2007)\n", KGRN);
	printf("%sMission: Impossible - Fallout (2018)\n", KGRN);
	printf("%sO Pai Tirano (1941)\n", KGRN);
	printf("%sOcean's 8 (2018)\n", KGRN);
	printf("%sPokémon The Movie: Everyone's Story (2018)\n", KRED);
	printf("%sPokémon The Movie: I Choose You! (2017)\n", KGRN);
	printf("%sRampage (2018)\n", KGRN);
	printf("%sSkyscraper (2018)\n", KGRN);
	printf("%sTag (2018)\n", KGRN);
	printf("%sThe Boss (2016)\n", KGRN);
	printf("%sThe Commuter (2018)\n", KGRN);
	printf("%sThe Disaster Artist (2017)\n", KGRN);
	printf("%sThe First Purge (2018)\n", KRED);
	printf("%sThe Gift (2015)\n", KGRN);
	printf("%sThe Post (2017)\n", KGRN);
	printf("%sThe Shape Of Water (2017)\n", KGRN);
	printf("%sThe Spy Who Dumped Me (2018)\n", KGRN);
	printf("%sThe Vow (2012)\n", KGRN);
	printf("%sThe Wedding Ringer (2015)\n", KGRN);
	printf("%sThis Means War (2012)\n", KGRN);
	printf("%sThor: Ragnarok (2017)\n", KGRN);
	printf("%sThoroughbreds (2017)\n", KGRN);
	printf("%sThree Billboards Outside Ebbing, Missouri (2017)\n", KGRN);
	printf("%sTrespass (2011)\n", KGRN);
	printf("%sVenom (2018)\n", KRED);

	printf("\n\n%sMovies watched in 2017:\n\n", KNRM);

	printf("%s5 Centimeters Per Second (2007)\n", KGRN);
	printf("%sA Long Way Down (2014)\n", KGRN);
	printf("%sAlien: Covenant (2017)\n", KGRN);
	printf("%sAllied (2016)\n", KGRN);
	printf("%sAnalyze This (1999)\n", KGRN);
	printf("%sArrival (2016)\n", KGRN);
	printf("%sBad Words (2013)\n", KGRN);
	printf("%sBaywatch (2017)\n", KGRN);
	printf("%sBruce Almighty (2003)\n", KGRN);
	printf("%sCars 3 (2017)\n", KGRN);
	printf("%sCrash (2004)\n", KGRN);
	printf("%sDaddy's Home (2015)\n", KGRN);
	printf("%sDinner For Schmucks (2010)\n", KGRN);
	printf("%sDoctor Strange (2016)\n", KGRN);
	printf("%sDrive (2011)\n", KGRN);
	printf("%sFantastic Beasts And Where To Find Them (2016)\n", KGRN);
	printf("%sFlorence Foster Jenkins (2016)\n", KGRN);
	printf("%sGet Out (2017)\n", KGRN);
	printf("%sGuardians Of The Galaxy Vol. 2 (2017)\n", KGRN);
	printf("%sGun Shy (2000)\n", KGRN);
	printf("%sHacksaw Ridge (2016)\n", KGRN);
	printf("%sHidden Figures (2016)\n", KGRN);
	printf("%sIndiana Jones And The Last Crusade (1989)\n", KGRN);
	printf("%sIndiana Jones And The Temple Of Doom (1984)\n", KGRN);
	printf("%sJoe Somebody (2001)\n", KGRN);
	printf("%sJuno (2007)\n", KGRN);
	printf("%sJustice League (2017)\n", KGRN);
	printf("%sKicking & Screaming (2005)\n", KGRN);
	printf("%sKidnap (2017)\n", KGRN);
	printf("%sKillers (2010)\n", KGRN);
	printf("%sKingsman: The Golden Circle (2017)\n", KGRN);
	printf("%sKong: Skull Island (2017)\n", KGRN);
	printf("%sLa La Land (2016)\n", KGRN);
	printf("%sLogan (2017)\n", KGRN);
	printf("%sManchester By The Sea (2016)\n", KGRN);
	printf("%sMisery (1990)\n", KGRN);
	printf("%sMoana (2016)\n", KGRN);
	printf("%sMoonlight (2016)\n", KGRN);
	printf("%sMystic River (2003)\n", KGRN);
	printf("%sNocturnal Animals (2016)\n", KGRN);
	printf("%sPassengers (2016)\n", KGRN);
	printf("%sPirates Of The Caribbean: Dead Men Tell No Tales (2017)\n", KGRN);
	printf("%sPirates Of The Caribbean: On Stranger Tides (2011)\n", KGRN);
	printf("%sPlaying For Keeps (2012)\n", KGRN);
	printf("%sPower Rangers (2017)\n"; KGRN);
	printf("%sRogue One: A Star Wars Story (2016)\n", KGRN);
	printf("%sSpider-Man: Homecoming (2017)\n", KGRN);
	printf("%sStar Wars: Episode VIII – The Last Jedi (2017)\n", KGRN);
	printf("%sStorks (2016)\n", KGRN);
	printf("%sThe Adjustment Bureau (2011)\n", KGRN);
	printf("%sThe Age Of Adaline (2015)\n", KGRN);
	printf("%sThe Bone Collector (1999)\n", KGRN);
	printf("%sThe Change-Up (2011)\n", KGRN);
	printf("%sThe Five-Year Engagement (2012)\n", KGRN);
	printf("%sThe Garden Of Words (2013)\n", KGRN);
	printf("%sThe Girl On The Train (2016)\n", KGRN);
	printf("%sThe Great Wall (2016)\n", KGRN);
	printf("%sThe Hitman's Bodyguard (2017)\n", KGRN);
	printf("%sThe Jungle Book (2016)\n", KGRN);
	printf("%sThe Lego Batman Movie (2017)\n", KGRN);
	printf("%sThe Lucky One (2012)\n", KGRN);
	printf("%sThe Mountain Between Us (2017)\n", KGRN);
	printf("%sThe Mummy (2017)\n", KGRN);
	printf("%sThe Next Three Days (2010)\n", KGRN);
	printf("%sThe Other Woman (2009)\n", KGRN);
	printf("%sThe Return (2006)\n", KGRN);
	printf("%sThe Snowman (2017)\n", KGRN);
	printf("%sTrust Me (2013)\n", KGRN);
	printf("%sTwo For The Money (2005)\n", KGRN);
	printf("%sUnknown (2011)\n", KGRN);
	printf("%sWar For The Planet Of The Apes (2017)\n", KGRN);
	printf("%sWhile She Was Out (2008)\n", KGRN);
	printf("%sWhy Him? (2016)\n", KGRN);
	printf("%sWolf Children (2012)\n", KGRN);
	printf("%sWonder (2017)\n", KGRN);
	printf("%sWonder Woman (2017)\n", KGRN);
	printf("%sYour Name (2016)\n", KGRN);

	printf("\n\n%sMovies watched in 2016:\n\n", KNRM);

	printf("%s10 Cloverfield Lane (2016)\n", KGRN);
	printf("%sA Little Bit Of Heaven (2011)\n", KGRN);
	printf("%sA Walk Among The Tombstones (2014)\n", KGRN);
	printf("%sAbout A Boy (2002)\n", KGRN);
	printf("%sAllegiant (2016)\n", KGRN);
	printf("%sBad Company (2002)\n", KGRN);
	printf("%sBatman: The Killing Joke (2016)\n", KGRN);
	printf("%sBatman v Superman: Dawn Of Justice (2016)\n", KGRN);
	printf("%sBefore I Go To Sleep (2014)\n", KGRN);
	printf("%sBlade Runner (1982)\n", KGRN);
	printf("%sCaptain America: Civil War (2016)\n", KGRN);
	printf("%sCaptain Fantastic (2016)\n", KGRN);
	printf("%sCast Away (2000)\n", KGRN);
	printf("%sCentral Intelligence (2016)\n", KGRN);
	printf("%sChanging Lanes (2002)\n", KGRN);
	printf("%sChild's Play (1988)\n", KGRN);
	printf("%sDeadpool (2016)\n", KGRN);
	printf("%sDeath Race (2008)\n", KGRN);
	printf("%sDon't Breathe (2016)\n", KGRN);
	printf("%sFinding Dory (2016)\n", KGRN);
	printf("%sFlirting With Disaster (1996)\n", KGRN);
	printf("%sFriday The 13th (2009)\n", KGRN);
	printf("%sGrimsby (2016)\n", KGRN);
	printf("%sHell Or High Water (2016)\n", KGRN);
	printf("%sHit And Run (2012)\n", KGRN);
	printf("%sHow Do You Know (2010)\n", KGRN);
	printf("%sIce Age: Collision Course (2016)\n", KGRN);
	printf("%sIdentity Thief (2013)\n", KGRN);
	printf("%sIt Follows (2014)\n", KGRN);
	printf("%sJoy (2015)\n", KGRN);
	printf("%sKubo And The Two Strings (2016)\n", KGRN);
	printf("%sKung Fu Panda 3 (2016)\n", KGRN);
	printf("%sLa Tortue Rouge (2016)\n", KGRN);
	printf("%sLights Out (2016)\n", KGRN);
	printf("%sMoney Monster (2016)\n", KGRN);
	printf("%sMorning Glory (2010)\n", KGRN);
	printf("%sNow You See Me 2 (2016)\n", KGRN);
	printf("%sOffice Christmas Party (2016)\n", KGRN);
	printf("%sOld School (2003)\n", KGRN);
	printf("%sPete's Dragon (2016)\n", KGRN);
	printf("%sPredestination (2014)\n", KGRN);
	printf("%sPride And Prejudice And Zombies (2016)\n", KGRN);
	printf("%sRaising Helen (2004)\n", KGRN);
	printf("%sRonaldo (2015)\n", KGRN);
	printf("%sRoom (2015)\n", KGRN);
	printf("%sSausage Party (2016)\n", KGRN);
	printf("%sScary Movie 5 (2013)\n", KGRN);
	printf("%sSecret In Their Eyes (2015)\n", KGRN);
	printf("%sSeeking Justice (2011)\n", KGRN);
	printf("%sSicario (2015)\n", KGRN);
	printf("%sSnowden (2016)\n", KGRN);
	printf("%sSpotlight (2015)\n", KGRN);
	printf("%sSteve Jobs (2015)\n", KGRN);
	printf("%sSuicide Squad (2016)\n", KGRN);
	printf("%sSully (2016)\n", KGRN);
	printf("%sTeenage Mutant Ninja Turtles: Out Of The Shadows (2016)\n", KGRN);
	printf("%sThe Angry Birds Movie (2016)\n", KGRN);
	printf("%sThe Beaver (2011)\n", KGRN);
	printf("%sThe Best Exotic Marigold Hotel (2011)\n", KGRN);
	printf("%sThe Big Short (2015)\n", KGRN);
	printf("%sThe Hunger Games: Mockingjay - Part 2 (2015)\n", KGRN);
	printf("%sThe Legend Of Tarzan (2016)\n", KGRN);
	printf("%sThe Nice Guys (2016)\n", KGRN);
	printf("%sThe Other Guys (2010)\n", KGRN);
	printf("%sThe Peanuts Movie (2015)\n", KGRN);
	printf("%sThe Purge: Election Year (2016)\n", KGRN);
	printf("%sThe Revenant (2015)\n", KGRN);
	printf("%sThe Secret Life Of Pets (2016)\n", KGRN);
	printf("%sThis Is 40 (2012)\n", KGRN);
	printf("%sTomorrowland (2015)\n", KGRN);
	printf("%sTrumbo (2015)\n", KGRN);
	printf("%sWar Dogs (2016)\n", KGRN);
	printf("%sX-Men: Apocalypse (2016)\n", KGRN);
	printf("%sYou Again (2010)\n", KGRN);
	printf("%sZootopia (2016)\n", KGRN);

	printf("\n\n%sMovies watched in 2015:\n\n", KNRM);

	printf("%sAnt-Man (2015)\n", KGRN);
	printf("%sAvengers: Age Of Ultron (2015)\n", KGRN);
	printf("%sBatman: The Dark Knight Returns, Part 1 (2012)\n", KGRN);
	printf("%sBatman: The Dark Knight Returns, Part 2 (2013)\n", KGRN);
	printf("%sBig Hero 6 (2014)\n", KGRN);
	printf("%sBirdman: Or (The Unexpected Virtue Of Ignorance) (2014)\n", KGRN);
	printf("%sCake (2014)\n", KGRN);
	printf("%sCapitão Falcão (2015)\n", KGRN);
	printf("%sCarrie (2013)\n", KGRN);
	printf("%sCars (2006)\n", KGRN);
	printf("%sCars 2 (2011)\n", KGRN);
	printf("%sCitizenfour (2014)\n", KGRN);
	printf("%sDragon Ball Z: Resurrection 'F' (2015)\n", KGRN);
	printf("%sEx Machina (2015)\n", KGRN);
	printf("%sFantastic Four (2015)\n", KGRN);
	printf("%sFifty Shades Of Grey (2015)\n", KGRN);
	printf("%sGet Hard (2015)\n", KGRN);
	printf("%sHomefront (2013)\n", KGRN);
	printf("%sHorrible Bosses 2 (2014)\n", KGRN);
	printf("%sHot Pursuit (2015)\n", KGRN);
	printf("%sI Love You, Man (2009)\n", KGRN);
	printf("%sIn A World... (2013)\n", KGRN);
	printf("%sInherent Vice (2014)\n", KGRN);
	printf("%sInside Out (2015)\n", KGRN);
	printf("%sInsurgent (2015)\n", KGRN);
	printf("%sIntolerable Cruelty (2003)\n", KGRN);
	printf("%sJohn Wick (2014)\n", KGRN);
	printf("%sJupiter Ascending (2015)\n", KGRN);
	printf("%sJurassic World (2015)\n", KGRN);
	printf("%sKick-Ass 2 (2013)\n", KGRN);
	printf("%sKingsman: The Secret Service (2015)\n", KGRN);
	printf("%sKramer vs. Kramer (1979)\n", KGRN);
	printf("%sMad Max: Fury Road (2015)\n", KGRN);
	printf("%sMadagascar (2005)\n", KGRN);
	printf("%sMarried Life (2007)\n", KGRN);
	printf("%sMaze Runner: The Scorch Trials (2015)\n", KGRN);
	printf("%sMission: Impossible - Rogue Nation (2015)\n", KGRN);
	printf("%sMud (2012)\n", KGRN);
	printf("%sNight At The Museum: Secret Of The Tomb (2014)\n", KGRN);
	printf("%sO Pátio Das Cantigas (2015)\n", KGRN);
	printf("%sOcean's Eleven (2001)\n", KGRN);
	printf("%sOcean's Thirteen (2007)\n", KGRN);
	printf("%sOcean's Twelve (2004)\n", KGRN);
	printf("%sOlympus Has Fallen (2013)\n", KGRN);
	printf("%sPaul Blart: Mall Cop 2 (2015)\n", KGRN);
	printf("%sPixels (2015)\n", KGRN);
	printf("%sPsycho (1960)\n", KGRN);
	printf("%sRio (2011)\n", KGRN);
	printf("%sRocky (1976)\n", KGRN);
	printf("%sRRRrrrr!!! (2004)\n", KGRN);
	printf("%sRun All Night (2015)\n", KGRN);
	printf("%sSan Andreas (2015)\n", KGRN);
	printf("%sSleepy Hollow (1999)\n", KGRN);
	printf("%sSpectre (2015)\n", KGRN);
	printf("%sStar Wars: Episode VII - The Force Awakens (2015)\n", KGRN);
	printf("%sStarsky & Hutch (2004)\n", KGRN);
	printf("%sStill Alice (2014)\n", KGRN);
	printf("%sStrangerland (2015)\n", KGRN);
	printf("%sTaken 3 (2014)\n", KGRN);
	printf("%sTed 2 (2015)\n", KGRN);
	printf("%sTerminator Genisys (2015)\n", KGRN);
	printf("%sThe Aviator (2004)\n", KGRN);
	printf("%sThe Blind Side (2009)\n", KGRN);
	printf("%sThe Dilemma (2011)\n", KGRN);
	printf("%sThe Good Dinosaur (2015)\n", KGRN);
	printf("%sThe Grand Budapest Hotel (2014)\n", KGRN); 
	printf("%sThe Hunger Games: Mockingjay - Part 1 (2014)\n", KGRN);
	printf("%sThe Imitation Game (2014)\n", KGRN);
	printf("%sThe Intern (2015)\n", KGRN);
	printf("%sThe Martian (2015)\n", KGRN);
	printf("%sThe Others (2001)\n", KGRN);
	printf("%sThe Ring (2002)\n", KGRN);
	printf("%sThe Theory Of Everything (2014)\n", KGRN);
	printf("%sThe Watch (2012)\n", KGRN);
	printf("%sUndercover Brother (2002)\n", KGRN);
	printf("%sWhile We're Young (2014)\n", KGRN);
	printf("%sWhiplash (2014)\n", KGRN);
	printf("%sWhite Bird In A Blizzard (2014)\n", KGRN);
	printf("%sWhite House Down (2013)\n", KGRN);
	printf("%sWild (2014)\n", KGRN);
	
	printf("\n\n%sMovies watched in 2014:\n\n", KNRM);
	
	printf("%s12 Monkeys (1995)\n", KGRN);
	printf("%s12 Years A Slave (2013)\n", KGRN);
	printf("%s22 Jump Street (2014)\n", KGRN);
	printf("%sA Million Ways To Die In The West (2014)\n", KGRN);
	printf("%sAbout Time (2013)\n", KGRN);
	printf("%sAmerican Hustle (2013)\n", KGRN);
	printf("%sAnchorman: The Legend Of Ron Burgundy (2004)\n", KGRN);
	printf("%sAnchorman 2: The Legend Continues (2013)\n", KGRN);
	printf("%sAugust: Osage County (2013)\n", KGRN);
	printf("%sBack To The Future Part III (1990)\n", KGRN);
	printf("%sBad Teacher (2011)\n", KGRN);
	printf("%sBlue Jasmine (2013)\n", KGRN);
	printf("%sBolt (2008)\n", KGRN);
	printf("%sBoyhood (2014)\n", KGRN);
	printf("%sBrothers (2009)\n", KGRN);
	printf("%sCaptain America: The Winter Soldier (2014)\n", KGRN);
	printf("%sCaptain Phillips (2013)\n", KGRN);
	printf("%sCloverfield (2008)\n", KGRN);
	printf("%sCouples Retreat (2009)\n", KGRN);
	printf("%sCrazy, Stupid, Love (2011)\n", KGRN);
	printf("%sDallas Buyers Club (2013)\n", KGRN);
	printf("%sDawn Of The Planet Of The Apes (2014)\n", KGRN);
	printf("%sDate Night (2010)\n", KGRN);
	printf("%sDelivery Man (2013)\n", KGRN);
	printf("%sDespicable Me 2 (2013)\n", KGRN);
	printf("%sDivergent (2014)\n", KGRN);
	printf("%sDragon Ball Z: Battle Of Gods (2013)\n", KGRN);
	printf("%sEdge Of Tomorrow (2014)\n", KGRN);
	printf("%sEnder's Game (2013)\n", KGRN);
	printf("%sEscape Plan (2013)\n", KGRN);
	printf("%sFargo (1996)\n", KGRN);
	printf("%sFinding Neverland (2004)\n", KGRN);
	printf("%sFour Christmases (2008)\n", KGRN);
	printf("%sFrozen (2013)\n", KGRN);
	printf("%sFury (2014)\n", KGRN);
	printf("%sGuardians Of The Galaxy (2014)\n", KGRN);
	printf("%sGodzilla (2014)\n", KGRN);
	printf("%sGone Girl (2014)\n", KGRN);
	printf("%sHer (2013)\n", KGRN);
	printf("%sHercules (2014)\n", KGRN);
	printf("%sHouse At The End Of The Street (2012)\n", KGRN);
	printf("%sHow To Train Your Dragon (2010)\n", KGRN);
	printf("%sHow To Train Your Dragon 2 (2014)\n", KGRN);
	printf("%sInside Llewyn Davis (2013)\n", KGRN);
	printf("%sIf Only (2004)\n", KGRN);
	printf("%sInterstellar (2014)\n", KGRN);
	printf("%sJack And Jill (2011)\n", KGRN);
	printf("%sKnocked Up (2007)\n", KGRN);
	printf("%sLet's Be Cops (2014)\n", KGRN);
	printf("%sLimitless (2011)\n", KGRN);
	printf("%sLocke (2013)\n", KGRN);
	printf("%sMission: Impossible - Ghost Protocol (2011)\n", KGRN);
	printf("%sModern Times (1936)\n", KGRN);
	printf("%sMovie 43 (2013)\n", KGRN);
	printf("%sNebraska (2013)\n", KGRN);
	printf("%sNeed For Speed (2014)\n", KGRN);
	printf("%sNightcrawler (2014)\n", KGRN);
	printf("%sNo Strings Attached (2011)\n", KGRN);
	printf("%sNoah (2014)\n", KGRN);
	printf("%sNon-Stop (2014)\n", KGRN);
	printf("%sPhilomena (2013)\n", KGRN);
	printf("%sPrince Of Persia: The Sands Of Time (2010)\n", KGRN);
	printf("%sPulp Fiction (1994)\n", KGRN);
	printf("%sRatatouille (2007)\n", KGRN);
	printf("%sRoboCop (2014)\n", KGRN);
	printf("%sSaving Private Ryan (1998)\n", KGRN);
	printf("%sSex Tape (2014)\n", KGRN);
	printf("%sShort Term 12 (2013)\n", KGRN);
	printf("%sSnow White And The Huntsman (2012)\n", KGRN);
	printf("%sSpirited Away (2001)\n", KGRN);
	printf("%sStep Brothers (2008)\n", KGRN);
	printf("%sStar Trek (2009)\n", KGRN);
	printf("%sTangled (2010)\n", KGRN);
	printf("%sTeenage Mutant Ninja Turtles (2014)\n", KGRN);
	printf("%sTerminator 2: Judgment Day (1991)\n", KGRN);
	printf("%sThe Amazing Spiderman 2 (2014)\n", KGRN);
	printf("%sThe Call (2013)\n", KGRN);
	printf("%sThe Campaign (2012)\n", KGRN);
	printf("%sThe Croods (2013)\n", KGRN);
	printf("%sThe Ex (2006)\n", KGRN);
	printf("%sThe Fault In Our Stars (2014)\n", KGRN);
	printf("%sThe Girl Who Leapt Through Time (2006)\n", KGRN);
	printf("%sThe Grey (2011)\n", KGRN);
	printf("%sThe Hobbit: The Battle Of The Five Armies (2014)\n", KGRN);
	printf("%sThe Impossible (2012)\n", KGRN);
	printf("%sThe Interview (2014)\n", KGRN);
	printf("%sThe Lego Movie (2014)\n", KGRN);
	printf("%sThe Lone Ranger (2013)\n", KGRN);
	printf("%sThe Maze Runner (2014)\n", KGRN);
	printf("%sThe Monuments Men (2014)\n", KGRN);
	printf("%sThe Other Woman (2014)\n", KGRN);
	printf("%sThe Purge (2013)\n", KGRN);
	printf("%sThe Purge: Anarchy (2014)\n", KGRN);
	printf("%sThe Secret Life Of Walter Mitty (2013)\n", KGRN);
	printf("%sThe Spectacular Now (2013)\n", KGRN);
	printf("%sThe Terminator (1984)\n", KGRN);
	printf("%sThe Wind Rises (2013)\n", KGRN);
	printf("%sThe Wolf Of Wall Street (2013)\n", KGRN);
	printf("%sThird Person (2013)\n", KGRN);
	printf("%sThor: The Dark World (2013)\n", KGRN);
	printf("%sTop Secret! (1984)\n", KGRN);
	printf("%sTranscendence (2014)\n", KGRN);
	printf("%sWALL-E (2008)\n", KGRN);
	printf("%sWatchmen (2009)\n", KGRN);
	printf("%sWeekend At Bernie's (1989)\n", KGRN);
	printf("%sWimbledon (2004)\n", KGRN);
	printf("%sWreck-It Ralph (2012)\n", KGRN);
	printf("%sX-Men: Days Of Future Past (2014)\n", KGRN);

	printf("\n\n%sMovies watched from June to December 2013:\n\n", KNRM);
	
	printf("%s21 Jump Street (2012)\n", KGRN);
	printf("%s(500) Days Of Summer (2009)\n", KGRN);
	printf("%sBilly Elliot (2000)\n", KGRN);
	printf("%sBlack Swan (2010)\n", KGRN);
	printf("%sBlade (1998)\n", KGRN);
	printf("%sBrave (2012)\n", KGRN);
	printf("%sCowboys And Aliens (2011)\n", KGRN);
	printf("%sDead Poets Society (1989)\n", KGRN);
	printf("%sDespicable Me (2010)\n", KGRN);
	printf("%sDon Jon (2013)\n", KGRN);
	printf("%sDon't Say A Word (2001)\n", KGRN);
	printf("%sElysium (2013)\n", KGRN);
	printf("%sFight Club (1999)\n", KGRN);
	printf("%sFinal Destination 5 (2011)\n", KGRN);
	printf("%sForgetting Sarah Marshall (2008)\n", KGRN);
	printf("%sFriends With Benefits (2011)\n", KGRN);
	printf("%sFriends With Money (2006)\n", KGRN);
	printf("%sGravity (2013)\n", KGRN);
	printf("%sIce Age 4 (2012)\n", KGRN);
	printf("%sJack Reacher (2012)\n", KGRN);
	printf("%sJobs (2013)\n", KGRN);
	printf("%sKick-Ass (2010)\n", KGRN);
	printf("%sLego Batman: The Movie – DC Super Heroes Unite (2013)\n", KGRN);
	printf("%sLove Happens (2009)\n", KGRN);
	printf("%sMan Of Steel (2013)\n", KGRN);
	printf("%sMemento (2000)\n", KGRN);
	printf("%sMonsters University (2013)\n", KGRN);
	printf("%sNow You See Me (2013)\n", KGRN);
	printf("%sOblivion (2013)\n", KGRN);
	printf("%sPacific Rim (2013)\n", KGRN);
	printf("%sPicture Perfect (1997)\n", KGRN);
	printf("%sPrisoners (2013)\n", KGRN);
	printf("%sPuss In Boots (2011)\n", KGRN);
	printf("%sRango (2011)\n", KGRN);
	printf("%sReal Steel (2011)\n", KGRN);
	printf("%sRope (1948)\n", KGRN);
	printf("%sRush (2013)\n", KGRN);
	printf("%sSharknado (2013)\n", KGRN);
	printf("%sThe Brass Teapot (2012)\n", KGRN);
	printf("%sThe Girl With The Dragon Tattoo (2011)\n", KGRN);
	printf("%sThe Heat (2013)\n", KGRN);
	printf("%sThe Hobbit: The Desolation Of Smaug (2013)\n", KGRN);
	printf("%sThe Hunger Games: Catching Fire (2013)\n", KGRN);
	printf("%sThe Internship (2013)\n", KGRN);
	printf("%sThe Nightmare Before Christmas (1993)\n", KGRN);
	printf("%sThe Pallbearer (1996)\n", KGRN);
	printf("%sThe Prestige (2006)\n", KGRN);
	printf("%sThe Room (2003)\n", KGRN);
	printf("%sThe Shawshank Redemption (1994)\n", KGRN);
	printf("%sThe Town (2010)\n", KGRN);
	printf("%sThe Wolverine (2013)\n", KGRN);
	printf("%sThis Is The End (2013)\n", KGRN);
	printf("%sThree Amigos! (1986)\n", KGRN);
	printf("%sTransformers (2007)\n", KGRN);
	printf("%sTriangle (2009)\n", KGRN);
	printf("%sUp In The Air (2009)\n", KGRN); 
	printf("%sWarm Bodies (2013)\n", KGRN);
	printf("%sWe're The Millers (2013)\n", KGRN);
	printf("%sWinter's Bone (2010)\n", KGRN);
	printf("%sWorld War Z (2013)\n", KGRN);
	printf("%sX-Men: First Class (2011)\n", KGRN);
	printf("%sX-Men Origins: Wolverine (2009)\n", KGRN);
	
	printf("%s\n", KNRM);
	
	exit(0);
}
